name: Execute Lint Formatting

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lintfmt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Create temporary VERSION file
      run: |
        echo "0.0.0" > VERSION

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pylint
        pip install -r requirements-dev.txt

    - name: Execute Lint Formatting
      run: make lintfmt
